### ISSUE TITLE
3 Specify research data 

### ISSUE THREAD

**Issue by lpandath** [tuwien-csd/damap-frontend#275] opened 2024-08-01 15:14 UTC
**Changes**
Add the capability to include and export **Description Field** for datasets within the DMP. This will make it practical for readers to see precise information about the datasets, improving the usability and clarity of the data.

**Additional notes**
The current issue is that the Description field for datasets is not being exported, rendering it essentially useless.

**Assumptions**
List any assumptions that you are aware of but still need to be reviewed.

**Acceptance Criteria**
When exporting datasets, the 'description field' should be included in the export file.

**Risks? (optional)**
Potential risks and how to best mitigate them.

**Comment by rekt-hard** [comment] 2024-08-05 13:48
Duplicate of tuwien-csd/damap-backend/issues/230

**Closed as completed by rekt-hard** 2024-08-05 13:48 UTC
Labels: feature
